from skimage import transform as sktrans
from skimage import filters as skfil
from skimage import exposure as skexp
from skimage import measure as skmes
from skimage import segmentation as skseg
from skimage import restoration as skres
from skimage import feature as skfeat
from skimage import registration as skreg
from skimage import morphology as skmorph
from skimage import graph as skgraph